---
##############################
# Instance configuration
#
# See man page for details on named instances. Also used for file suffixing;
# example: varnish.params will be deployed as varnish-{{ varnish_instance.name }}.params
#
varnish_instance:
  name: prod
  port: 6081
  admin_port: 6082
  backend_port: 8080
  backend_host: localhost     # this is optional; defaults to localhost if unspecified

##############################
## Listener settings

# Default address to bind to. Blank address means all IPv4 and IPv6 interfaces, otherwise specify a host name,
# an IPv4 dotted quad, or an IPv6 address in brackets.
varnish_listen_address: 127.0.0.1

# Admin interface listen address
varnish_admin_listen_address: 127.0.0.1

##############################
## VCL config

# Default varnish instance configuration template
varnish_vcl_template: magento2.vcl.j2

# Backend reponse ttl in seconds
varnish_beresp_ttl: 86400

# Health check URI (for pass through only; no health checks in VCL currently)
varnish_health_check: /health.php

# List of hosts used in the vcl template perge acl
varnish_acl_purge_hosts: [ localhost ]

# Array of hosts used in profile acl; supports use of Blackfire profiling when needed
#
# At minimum this should both include "localhost" when varnish resides behind nginx or another
# similar proxy on the same server and the actual client IPs which should be allowed to bust
# through varnish when profiling. When set, the appropriate VCL code will be included (assuming
# use of default VCL template) and requests where client.ip and X-Real-IP are BOTH on the list
# of allowed IPs will be allowed through. All other requests with a X-Blackfire-Query header
# will be denied.
#
varnish_acl_profile_hosts: false

##############################
## Configurable varnish params

# Cache size: in bytes, optionally using k / M / G / T suffix
varnish_storage_size: 4G

# Default TTL used when the backend does not specify one
varnish_ttl: 120

# The minimum number of worker threads to start
varnish_min_threads: 50

# The Maximum number of worker threads to start
varnish_max_threads: 1000

# Must be larger than both http_resp_hdr_len and http_resp_size; defaulting to 256k
varnish_workspace_backend: 260096

# Defaulting to 192k vs varnish default of 32k to support large magento response headers
varnish_http_resp_size: 196608

# Defaulting to 128k vs varnish default of 8k to support the lengthy X-Magento-* headers
varnish_http_resp_hdr_len: 131072

# When using secure URLs on the frontend, this is neccessary to prevent backend connect failures
varnish_esi_ignore_https: yes
