
- name: create user {{ www_user_name }}
  user:
    name: "{{ www_user_name }}"
    home: "{{ www_user_home }}"
    groups: "{{ www_user_groups | join(',') }}"
    append: yes
    shell: /bin/bash
    generate_ssh_key: yes

- name: import ssh keys for {{ www_user_name }}
  authorized_key:
    user: "{{ www_user_name }}"
    key: "{{ lookup('file', '{{ item }}') }}"
  with_items: "{{ www_user_ssh_keys }}"

# replace www- out of username for data dir name if present
- set_fact: www_user_web_dir={{ www_user_name|replace("www-", "") }}
  when: www_user_name != "www-data"

# use standard /var/www/html when www-data is used
- set_fact: www_user_web_dir=html
  when: www_user_name == "www-data"

- name: create /var/www/{{ www_user_web_dir }}
  file:
    path: /var/www/{{ www_user_web_dir }}
    owner: "{{ www_user_name }}"
    group: "{{ www_user_name }}"
    mode: 0751
    state: directory

- name: "append ~{{ www_user_name }}/bash_profile dir change"
  lineinfile:
    line: "cd /var/www/{{ www_user_web_dir }}"
    dest: ~{{ www_user_name }}/.bash_profile
