---
redis_version: "30"
redis_package_name: "redis{{ redis_version }}u"

redis_instance:
  name: obj
  port: 6379
  save: no

redis_maxmemory: 1gb

# Key/value hash of settings for /etc/redis-{{ redis_instance.name }}.conf
# This can be overridden or passed in when specifying the role to apply
redis_instance_config: []

# Key/value hash of settings for /etc/redis-base.conf
redis_config:
  - daemonize: "yes"
  - timeout: "0"
  - loglevel: "notice"
  - databases: "2"
  - rdbcompression: "no"
  - dbfilename: "dump.rdb"
  - maxmemory-policy: "volatile-lru"
  - appendonly: "no"
  - appendfsync: "everysec"
  - no-appendfsync-on-rewrite: "no"
  - slowlog-log-slower-than: "10000"
  - slowlog-max-len: "1024"
  - list-max-ziplist-entries: "512"
  - list-max-ziplist-value: "64"
  - set-max-intset-entries: "512"
  - zset-max-ziplist-entries: "128"
  - zset-max-ziplist-value: "64"
  - activerehashing: "yes"
  - slave-serve-stale-data: "yes"
  - auto-aof-rewrite-percentage: "100"
  - auto-aof-rewrite-min-size: "64mb"
  - tcp-backlog: "511"
  - tcp-keepalive: "0"
  - repl-disable-tcp-nodelay: "no"
